"""Concise HTML research-report builder.

Composes small, labelled sections (configuration, dataset, strategy
parameters, gross/net performance, costs, slippage, drawdown, trade stats,
benchmark, in-sample / out-of-sample, parameter sensitivity) into a single
self-contained HTML page. The builders here are intentionally generic so the
research scripts decide the content; this module only renders it.

All research output must be clearly labelled as historical/synthetic evidence.
"""
from __future__ import annotations

import html
from decimal import Decimal


def fmt(value: Decimal | None | float | int | str, suffix: str = "") -> str:
    """Format a metric for a report; None renders as 'n/a'."""
    if value is None:
        return "n/a"
    if isinstance(value, Decimal):
        if not value.is_finite():
            return "Infinity" if value > 0 else "-Infinity"
        return f"{value:f}{suffix}"
    return f"{value}{suffix}"


def escape(value: str) -> str:
    return html.escape(value)


def card(num: str, label: str, tone: str = "neutral") -> str:
    return f"<div class='card {tone}'><div class='num'>{escape(num)}</div><div class='lbl'>{escape(label)}</div></div>"


def kv_rows(pairs: list[tuple[str, str]]) -> str:
    return "".join(
        f"<tr><th>{escape(k)}</th><td class='num'>{escape(v)}</td></tr>" for k, v in pairs
    )


def table(headers: list[str], rows: list[list[str]]) -> str:
    head = "".join(f"<th>{escape(h)}</th>" for h in headers)
    body = ""
    for row in rows:
        body += "<tr>" + "".join(f"<td class='num'>{escape(cell)}</td>" for cell in row) + "</tr>"
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


CSS = """
* { box-sizing: border-box; }
body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; background: #f6f8fa; color: #1f2328; }
.wrap { max-width: 1100px; margin: 0 auto; padding: 24px 16px 64px; }
header { padding: 20px 24px; border-radius: 10px; background: linear-gradient(135deg, #5b0f00, #7a2a00); color: #fff; margin-bottom: 20px; }
header h1 { margin: 0; font-size: 22px; }
header p { margin: 6px 0 0; opacity: .9; font-size: 13px; }
.cards { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 10px; }
.card { flex: 1 1 140px; background: #fff; border: 1px solid #d0d7de; border-radius: 10px; padding: 12px 16px; }
.card .num { font-size: 20px; font-weight: 700; }
.card .lbl { font-size: 11px; color: #57606a; text-transform: uppercase; letter-spacing: .04em; }
.card.ok .num { color: #1a7f37; }
.card.bad .num { color: #cf222e; }
.card.neutral .num { color: #0d1117; }
section { background: #fff; border: 1px solid #d0d7de; border-radius: 10px; padding: 18px 20px; margin-bottom: 20px; }
section h2 { margin: 0 0 12px; font-size: 16px; border-bottom: 1px solid #eaeef2; padding-bottom: 10px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid #eaeef2; }
th { background: #f6f8fa; font-size: 12px; text-transform: uppercase; letter-spacing: .03em; color: #57606a; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.note { background: #fff8e6; border: 1px solid #e3c86a; border-radius: 8px; padding: 12px 16px; font-size: 12px; margin-bottom: 20px; }
.footer { font-size: 12px; color: #57606a; text-align: center; margin-top: 8px; }
"""


def build_research_html(
    *,
    title: str,
    blocks: list[str],
    disclaimer: str,
    generated_at: str,
) -> str:
    """Assemble a labelled research report page."""
    sections = "".join(blocks)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<style>{CSS}</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>{escape(title)}</h1>
    <p>Generated {escape(generated_at)} &middot; paper-trading only &middot; deterministic synthetic data</p>
  </header>
  <div class="note"><strong>Disclaimer:</strong> {escape(disclaimer)}</div>
  {sections}
  <div class="footer">Generated by the strategy-research framework &middot; paper-trading only &middot; no secret data</div>
</div>
</body>
</html>"""


def metrics_cards(metrics) -> str:
    """A compact set of headline metric cards."""
    return "".join([
        card(fmt(metrics.net_pnl), "Net P&L", "ok" if (metrics.net_pnl or 0) >= 0 else "bad"),
        card(fmt(metrics.net_return_pct, "%"), "Net Return"),
        card(fmt(metrics.cagr_pct, "%"), "CAGR (annualized)"),
        card(fmt(metrics.max_drawdown), "Max Drawdown", "bad"),
        card(fmt(metrics.max_drawdown_pct, "%"), "Max DD %", "bad"),
        card(str(metrics.num_trades), "Trades"),
        card(fmt(metrics.expectancy), "Expectancy"),
        card(fmt(metrics.sharpe_ratio), "Sharpe (ann.)"),
    ])